// <auto-generated />
using Gruppe20App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gruppe20App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504145543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Gruppe20App.Models.Organisasjon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisasjonsform")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisasjonsnummer")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organisasjoner");
                });

            modelBuilder.Entity("Gruppe20App.Models.RollePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganisasjonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganisasjonId");

                    b.ToTable("RollePersoner");
                });

            modelBuilder.Entity("Gruppe20App.Models.RollePerson", b =>
                {
                    b.HasOne("Gruppe20App.Models.Organisasjon", "Organisasjon")
                        .WithMany("RollePersoner")
                        .HasForeignKey("OrganisasjonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisasjon");
                });

            modelBuilder.Entity("Gruppe20App.Models.Organisasjon", b =>
                {
                    b.Navigation("RollePersoner");
                });
#pragma warning restore 612, 618
        }
    }
}
